### ISSUE TITLE
[Help] How does colorscheme get added to the config here? 

### ISSUE THREAD

**Issue by KarthikNayak** [hmajid2301/dotfiles#1]
https://github.com/hmajid2301/dotfiles/blob/16519585796e8db3d6a3cc679a5b5fd352948911/hosts/framework/home.nix#L52

Hello,

I've been trying to set up NixOS for the first time, I came by your repository and was trying to learn/copy. How does this particular line work? I see that you setup `config.colorscheme`. But I couldn't find any code around creating the `colorscheme` option. So how does this work?

**Comment by hmajid2301** [comment]
HI Karthik,

This option comes from the nix-colors "repo" (flake).  Which is imported in my `home-manager/default.nix`.

**Comment by KarthikNayak** [comment]
Hey @hmajid2301,

Ah! Makes sense now. Thanks for the tip!
