### ISSUE TITLE
GTK_THEME might have an incorrect value

### ISSUE THREAD

**Issue by cmetz** [hmajid2301/dotfiles#3]
Hey Haseeb,

I'm trying to build my own Hyprland configuration and I'm using your dotfiles for inspiration. I had trouble getting Firefox to automatically detect and use the dark theme, including making sure that context menus and save dialogs are in dark mode. I ended up resolving this by changing the following setting:
```
home.sessionVariables.GTK_THEME = "Adwaita-dark";
to 
home.sessionVariables.GTK_THEME = "Adwaita:dark";
```
This solved all the problems for me. It's hard to find documentation on that variable, but Arch uses the colon syntax. Maybe it's also relevant for your configuration.

While writing, I also discovered that you are already using the dconf ... color-scheme = prefer-dark. However, during my manual hacking and testing, it seemed that this did not fix the context menus issues, or perhaps setting it later does not affect every part of the system.

**Comment by hmajid2301** [comment]
Thank you very much for posting this! I will try it now, yeh certain parts of the dotfiles are  defo a work in progress :see_no_evil:

**Comment by cmetz** [comment]
Yeah, it's really complicated to get it work properly. After adding a dconf with color-scheme = prefer-dark to the nix config. it seems that the GTK_THEME is not required anymore fore firefox, but i also installed the xdg portal gtk.

 Yesterday i found out that screensharing on hyperland / wayland is way to slow, i think i will stay on bspwm and x for a while :(

**Comment by hmajid2301** [comment]
what was your issue? what do you mean too slow?

**Comment by cmetz** [comment]
I simply started a Google Hangout, I believe in fullscreen, and then just typed into a terminal. I noticed that there was a significantly higher latency between input and display (google hangout window in local browser). On my other computer using X, it was much faster. There could be many reasons for this.

However, I also had issues with screen sharing when I went fullscreen in Hyprland and then returned. The sharing would break. Overall, it's rather unsatisfactory for my home office job. :(

**Comment by hmajid2301** [comment]
yeh i do find it a bit fidly!

```
sleep 1
  killall -e xdg-desktop-portal-hyprland
  killall -e xdg-desktop-portal-wlr
  killall xdg-desktop-portal
  /usr/libexec/xdg-desktop-portal-hyprland &
  sleep 2
  /usr/libexec/xdg-desktop-portal &
  ```
  
  usually running this fixes it for me in google meet but either way i get not wanting to deal with it for work
